app:
  sync_interval: 5m
  username_replacements:
    - from: "@acme.com"
      to: ""
    - from: "@"
      to: ":"
  groupname_replacements:
    - from: "|all"
      to: ""
  remove_limit: 10
  ban_before_remove_duration: 168h # 7d

keycloak:
  url: "http://localhost:8080"
  realm: "test"
  client_id: "test"
  client_secret_env_var: "KEYCLOAK_CLIENT_SECRET"
  users_attribute_filter: "username:test_ email:@acme.com" # attributes search filter https://www.keycloak.org/docs/latest/server_admin/index.html#listing-users
  users_group_filter: "^test_.*" # regexp filter
  groups_filter: "^test_.*" # regexp filter

ytsaurus:
  proxy: localhost:10110
  apply_user_changes: true
  apply_group_changes: true
  apply_member_changes: true
  timeout: 1s
  log_level: DEBUG

logging:
  level: WARN
  is_production: true